/**
 * Create fake content for text pages
 */

var pages = [];

pages.push("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean in lacus nec purus luctus luctus non eu nibh. Quisque id lorem mi. Nunc eleifend, lacus gravida venenatis porta, risus risus venenatis massa, a scelerisque felis lectus at elit. Cras non lobortis metus. Aliquam vulputate nunc ut nisl tempor pretium. Proin id urna lorem. Vestibulum volutpat tortor eget nisl commodo aliquam. Vivamus pharetra est nec tortor eleifend, non suscipit purus porta. Nullam lacinia accumsan pulvinar. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed facilisis velit in dolor suscipit, id accumsan eros semper. Quisque rutrum orci dapibus bibendum hendrerit. Vestibulum consectetur molestie odio, ut dapibus sem eleifend in. Integer metus lacus, tempus eget commodo quis, lacinia id diam. Nunc bibendum eu ante ac pharetra. Etiam malesuada massa nibh, vel tincidunt eros cursus sit amet.");
pages.push("Integer vitae felis volutpat, fermentum mauris nec, hendrerit nisi. Donec lobortis nibh justo, ut tempor lectus elementum in. Aenean ut luctus nisl. Nullam sit amet venenatis neque. Mauris eget nunc ante. Morbi porttitor fermentum rutrum. Duis eros urna, varius nec vulputate nec, mattis at elit. Cras ut auctor erat. Aenean ut lobortis velit, ac lobortis dui. Nulla eu commodo leo, eget ornare sem. Nunc tempus erat sed malesuada tincidunt. Donec sed congue arcu. Curabitur commodo eros a lectus commodo laoreet.");
pages.push("Nunc varius finibus volutpat. Morbi tempus in magna ac laoreet. Phasellus posuere placerat tellus vel consectetur. Vivamus tincidunt mattis ullamcorper. Phasellus quis sodales nisi, vitae tempus mauris. Aliquam semper convallis nisi et consequat. Aliquam congue mauris vel metus hendrerit, ut laoreet metus porta. Donec molestie in risus eu finibus. Mauris in dui id mauris scelerisque varius vel nec nisl. Proin tempus metus sit amet lectus porttitor egestas. Nulla rhoncus lectus vel lobortis rhoncus. Mauris tristique sodales enim id ullamcorper. In semper enim ac tellus ornare, vel ultricies dui consectetur. Quisque nec tortor at urna accumsan euismod eget non nunc.");
pages.push("Morbi lacinia pellentesque nisi, quis efficitur nisi faucibus eu. Donec quis erat placerat, varius mi eget, vulputate arcu. Aenean scelerisque libero ut dolor aliquam pretium vitae nec dolor. Suspendisse at nunc lorem. In ut pretium nunc. Quisque imperdiet erat non dui vehicula venenatis. Cras commodo quam a metus luctus rhoncus. Duis efficitur mauris ac metus consectetur bibendum. In hac habitasse platea dictumst. Ut sagittis a velit vel molestie. Fusce porttitor, velit vel facilisis efficitur, erat mi interdum sapien, ac dictum nulla est a sapien. Vestibulum id mollis massa, nec lacinia magna. Curabitur vel metus lacinia, iaculis ligula in, luctus nisl. Suspendisse lacinia efficitur consequat. Curabitur ultricies odio vitae mauris ullamcorper, quis sodales eros tristique. Praesent sed semper magna.");
pages.push("Ut posuere orci sed vestibulum consequat. Cras ac purus ornare, sodales odio vel, malesuada magna. Pellentesque posuere metus ut magna auctor mattis. Proin eu suscipit neque, in pulvinar nisi. Aliquam eget mattis nisi. Etiam a enim vehicula, sodales dolor vitae, faucibus libero. Donec vitae felis massa. Nam in porta enim. Aliquam ut mi pharetra nunc lacinia suscipit. Cras faucibus lacus et urna feugiat pharetra.");

module.exports = pages;